carbonrater/mileage/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

urlpatterns = patterns('',
    
    url(r'^$', 'mileage.views.index', name='home'),

    url(r'^{0}$'.format(settings.LOGIN_PAGE), 'mileage.views.login', name='login',
        kwargs={'template_name':'login.html'}),
    url(r'^{0}$'.format(settings.LOGOUT_PAGE), 'django.contrib.auth.views.logout', name='logout',
        kwargs={'next_page':settings.BASE_URL}),

    url(r'^{0}$'.format(settings.ACCOUNT_PAGE), 
        'mileage.views.account', name='account'),
    
    url(r'^vehicle/(\d+)$', 'mileage.views.vehicle', name='vehicle'),
    url(r'^vehicle/(\d+)/edit$', 'mileage.views.vehicle_edit', name='vehicle_edit'),
    url(r'^vehicle/new$', 'mileage.views.vehicle_edit', name='vehicle_new'),
    
    url(r'^vehicle/(\d+)/mileage/(\d+)$', 'mileage.views.mileage_edit', name='mileage_edit'),
    url(r'^vehicle/(\d+)/mileage/new$', 'mileage.views.mileage_edit', name='mileage_new'),
    url(r'^vehicle/(\d+)/mileage/(\d+)/delete$', 'mileage.views.mileage_delete', name='mileage_delete'),
    
)

carbonrater/www/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'carbonrater.views.home', name='home'),
    # url(r'^carbonrater/', include('carbonrater.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'', include('mileage.urls')),

)

carbonrater/mileage/models.py
from datetime import date
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.aggregates import Max
from django.db.models.signals import post_save, post_delete
from django.dispatch.dispatcher import receiver
from django.utils.translation import ugettext_lazy as _
from south.modelsinspector import add_introspection_rules

class YearField(models.IntegerField):
    description = _("Integer")
    def get_internal_type(self):
        return "YearField"

    def formfield(self, **kwargs):
        defaults = {'min_value': 1990, 'max_value': date.today().year+5}
        defaults.update(kwargs)
        return super(YearField, self).formfield(**defaults)

add_introspection_rules([], ["^carbonrater\.mileage\.models\.YearField"])

class VehicleType(models.Model):
    year          = YearField()
    make          = models.CharField(max_length=100)
    model         = models.CharField(max_length=100)
    variant       = models.CharField(max_length=100)
    
    def name(self):
        return "{self.year} {self.make} {self.model} {self.variant}".format(self=self)
    
    def __str__(self):
        return self.name()

class Vehicle(models.Model):
    vehicle_type  = models.ForeignKey(VehicleType, blank=True, null=True, on_delete=models.SET_NULL)
    name          = models.CharField(max_length=100)
    owner         = models.ForeignKey(User, blank=False, null=False, editable=False)
    stated_mpg    = models.FloatField()
    actual_mpg    = models.FloatField(blank=True, null=True)
    mileage       = models.FloatField(default=0)
    
    @models.permalink
    def get_absolute_url(self):
        return ('mileage.views.vehicle', [str(self.id)])
    
    def __str__(self):
        return self.name

MILEAGE_ORDER_ERROR="Mileages and dates are out of order. You recorded {mileage.mileage} miles on {mileage.date}."
class MileageRecord(models.Model):
    vehicle       = models.ForeignKey(Vehicle, editable=False,
                    help_text='Vehicle')
    date          = models.DateField(
                    help_text='Date recorded')
    mileage       = models.FloatField(
                    help_text='Current mileage')
    gallons       = models.FloatField(blank=True, null=True,
                    help_text='Number of gallons filled')
    filled        = models.BooleanField(default=True,
                    help_text='True if tank was topped off')

    mpg           = models.FloatField(editable=False, blank=True, null=True,
                    help_text='Calculated MPG')

    def clean(self):
        prev_query = self.vehicle.mileagerecord_set.filter(date__lte=self.date).order_by('-date')
        if self.pk:
            prev_query = prev_query.exclude(pk=self.pk)
        if prev_query:
            prev_mileage = prev_query[0]
            if prev_mileage is not None and prev_mileage.mileage >= self.mileage:
                raise ValidationError(MILEAGE_ORDER_ERROR.format(mileage=prev_mileage))
    
        next_query = self.vehicle.mileagerecord_set.filter(date__gte=self.date).order_by('date')
        if self.pk:
            next_query = next_query.exclude(pk=self.pk)
        if next_query:
            next_mileage = next_query[0]
            if next_mileage is not None and next_mileage.mileage <= self.mileage:
                raise ValidationError(MILEAGE_ORDER_ERROR.format(mileage=next_mileage))

    class Meta:
        ordering = ['date']

carbonrater/mileage/views.py
from datetime import date
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.views import login as _login
from django.core.exceptions import ValidationError
from django.forms.fields import FloatField
from django.forms.forms import NON_FIELD_ERRORS
from django.forms.widgets import DateInput, TextInput
from django.http import HttpResponseForbidden, Http404
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template.context import RequestContext
from mileage import util
from mileage.models import Vehicle, MileageRecord
from mileage.widgets import NumericInput, CalendarInput
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext as _
from django.contrib import auth, messages

def index(request):
    if request.user.is_authenticated():
        return redirect('account')
    else:
        return redirect('login')

# User Account

def account(request, user=None):
    if user is None:
        user = request.user
    return render_to_response('account.html', {
        'user': user,
    },
    context_instance=RequestContext(request))

class UserForm(forms.ModelForm):
    class Meta:
        model = User

class LoginForm(AuthenticationForm):
    username = forms.CharField(label=_("Username"), max_length=30,
        widget=TextInput(attrs={'autocapitalize': 'off'}))

def login(*args, **kwargs):
    return _login(authentication_form=LoginForm, *args, **kwargs)

def account_edit(request, user=None):
    if user is None:
        user = request.user
    elif user != request.user:
        if not request.user.is_administrator:
            raise HttpResponseForbidden
    if request.method == 'POST':
        form = UserForm(request.POST, instance=user) 
        if form.is_valid():
            form.save()
            return redirect('account')
    else:
        form = UserForm(instance=request.user)

    return render_to_response('account_edit.html', {
        'form': form,
    },
    context_instance=RequestContext(request))

# Vehicle

def vehicle(request, vehicle_id):
    vehicle = get_object_or_404(Vehicle, pk=vehicle_id)
    mileage_form = None  
    if vehicle.owner == request.user:
        mileage_record = MileageRecord(
            date = date.today(),
        )
        mileage_form = MileageRecordForm(instance=mileage_record)
    return render_to_response('vehicle.html', {
        'vehicle': vehicle,
        'mileage_form': mileage_form,
    }, context_instance=RequestContext(request))
    
class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle        

def vehicle_edit(request, vehicle_id=None):
    vehicle = None
    if vehicle_id is not None:
        vehicle = get_object_or_404(Vehicle, pk=vehicle_id)
        if vehicle.owner_id != request.user.id:
            raise Http404()
    else:
        vehicle = Vehicle(owner=request.user)

    if request.method == 'POST':
        form = VehicleForm(request.POST, instance=vehicle) 
        if form.is_valid():
            form.save()
            return redirect('account')
    else:
        form = VehicleForm(instance=vehicle)

    return render_to_response('vehicle_edit.html', {
        'form': form,
        },
        context_instance=RequestContext(request))

# Mileage

class MileageRecordForm(forms.ModelForm):
    
    def add_error(self, error):
        self._errors[NON_FIELD_ERRORS] = self.error_class(error.messages)
        
    class Meta:
        model = MileageRecord
        widgets = {
            'date' : CalendarInput(),
            'mileage' : NumericInput(),
            'gallons' : NumericInput(),
        }

def get_mileage_record(request, vehicle_id, mileage_record_id=None):
    vehicle = get_object_or_404(Vehicle, pk=vehicle_id)
    if vehicle.owner_id != request.user.id:
        raise Http404("Not your vehicle")

    mileage_record = None
    if mileage_record_id is not None:
        mileage_record = get_object_or_404(MileageRecord, pk=mileage_record_id)
        if mileage_record.vehicle_id != vehicle.id:
            raise Http404("Vehicle/mileage mismatch")
    else:
        mileage_record = MileageRecord(vehicle=vehicle)
    return (vehicle, mileage_record)

def mileage_edit(request, vehicle_id, mileage_record_id=None):
    vehicle, mileage_record = get_mileage_record(request, vehicle_id, mileage_record_id)
    form = None
    if request.method == 'POST':
        # action is specified by name of submit button
        if 'cancel' in request.POST:
            return redirect(vehicle.get_absolute_url())
        elif 'delete' in request.POST:
            mileage_record.delete()
            util.update_mileages(vehicle)
            messages.info(request, "Deleted mileage record")
            return redirect(vehicle.get_absolute_url())
        else:
            form = MileageRecordForm(request.POST, instance=mileage_record) 
            if form.is_valid():
                mileage_record = form.save()
                util.update_mileages(vehicle)
                mileage_record = MileageRecord.objects.get(id=mileage_record.id)
                messages.info(request, "You got %.1f MPG" % mileage_record.mpg)
                return redirect(vehicle.get_absolute_url())
    else:
        form = MileageRecordForm(instance=mileage_record) 

    return render_to_response('mileage_edit.html', {
        'vehicle': vehicle,
        'form': form,
    },
    context_instance=RequestContext(request))

def mileage_delete(request, vehicle_id, mileage_record_id):
    vehicle, mileage_record = get_mileage_record(request, vehicle_id, mileage_record_id)
    mileage_record.delete()
    util.update_mileages(vehicle)
    return redirect(vehicle.get_absolute_url())

carbonrater/mileage/templates/account.html
{% extends "base.html" %}

{% block title %}{{ user.get_full_name }}{% endblock %}

{% block content %}
<h3>Active Since {{ user.date_joined|date }}</h3>

  <h4 class="header">Vehicles</h4>
  <div class="btn-group btn-group-vertical btn-group-vehicle">
    {% for vehicle in user.vehicle_set.all %}
      <a class="btn btn-block btn-vehicle" href="{{ vehicle.get_absolute_url }}">
        <h5>{{ vehicle.name }}</h5>
        <div class="mileage">{{ vehicle.mileage }}</div>
      </a>
    {% endfor %}
  </div>
  {% if user == request.user %}
  <div class="btn-toolbar">
    <a href="{% url 'vehicle_new' %}" class="btn">Add Vehicle</a>
  </div>
  {% endif %}

{% endblock %}

carbonrater/mileage/templates/account_edit.html
{% extends "base.html" %}

{% block title %}My Account{% endblock %}

{% block content %}
  <form method="POST">{% csrf_token %}
  <ul>
    {{ form.as_ul }}
    <li><input type="submit" value="Save" /></li>
  </ul>
  </form>  
{% endblock %}

carbonrater/mileage/templates/base.html
{% extends "base_base.html" %}

{% block css %}

  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}cr.css">
  
{% endblock %}
{% block js %}
  <script type="text/javascript">var IS_MOBILE = {{ is_mobile|yesno:"true,false"}};</script>
  <script type="text/javascript" 
    src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>
  <script type="text/javascript" 
    src="{{ STATIC_URL }}js/cr.js"></script>
{% endblock %}

{% block base_content %}
  <h2>{% block title %}{% endblock %}</h2>
  
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>
    {% endfor %}
  {% endif %}
  
  {% block content %}{% endblock %}
{% endblock %}

carbonrater/mileage/templates/base_base.html
<!doctype html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    {% block css %}
    {% endblock %}
    {% block js %}
    {% endblock %}
    <meta name="viewport" content="user-scalable=no, width=device-width" />
  </head>
  <body>

    {% block header %}
      {% include "header.html" %}
    {% endblock %}

    <div class="container">

      <div id="content">

        {% block base_content %}
        {% endblock %}
      
      </div>
      
      {% block footer %}
      {% include "footer.html" %}
      {% endblock %}
      
    </div>
  </body>
</html>

carbonrater/mileage/templates/footer.html
<div id="footer">
  &copy; 2012
</div>

carbonrater/mileage/templates/header.html
<div class="navbar navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="{% url 'home' %}">The Carbon Rater</a>
      
      <form class="navbar-form pull-right">
        {% if user.is_authenticated %}
          <a class="btn btn-small" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <a class="btn btn-small" href="{% url 'login' %}"><i class="icon-user"></i> Login</a>
        {% endif %}
      </form>
    </div>
  </div>
</div>

carbonrater/mileage/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Log In{% endblock %}

{% block content %}
<form method="post" class="form-horizontal">
{% csrf_token %}
<input type="hidden" name="next" value="{{ next }}" />
{{ form|crispy }}
<div class="btn-toolbar"><input type="submit" class="btn" value="Login" /></div>
</form>
{% endblock %}

carbonrater/mileage/templates/mileage_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ vehicle.name }}{% endblock %}

{% block content %}
  <form method="POST" class="form-horizontal" novalidate="novalidate">
    {% csrf_token %}
    <div class="panel">
      <div class="header">{{ form.instance|yesno:'Edit,Add' }} Mileage</div>
      <div class="body">
        {% csrf_token %}
        {{ form|crispy }}
          <div>
            <input type="submit" class="btn btn-primary" value="Save" />
            {% if form.instance %}
            <input type="submit" class="btn confirm" name="delete" value="Delete" />
            {% endif %}
            <input type="submit" class="btn" name="cancel" value="Cancel" />
          </div>
      </div>
    </div>
  </form>
{% endblock %}

carbonrater/mileage/templates/vehicle.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ vehicle.name }}{% endblock %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/css" 
  href="{{ STATIC_URL }}/jqplot/jquery.jqplot.css" />
{% endblock css %}

{% block js %}
{{ block.super }}
<script type="text/javascript" 
        src="{{ STATIC_URL }}/jqplot/jquery.jqplot.min.js"></script>
<script type="text/javascript" 
        src="{{ STATIC_URL }}/jqplot/plugins/jqplot.highlighter.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}/jqplot/plugins/jqplot.cursor.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}/jqplot/plugins/jqplot.dateAxisRenderer.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}/jqplot/plugins/jqplot.canvasTextRenderer.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}/jqplot/plugins/jqplot.canvasAxisTickRenderer.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}/jqplot/plugins/jqplot.canvasAxisLabelRenderer.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}/js/vehicle_chart.js"></script>
<script type="text/javascript">
var data = [
{% for mileagerecord in vehicle.mileagerecord_set.all %}
	[ {{ mileagerecord.date|date:"U" }}, 
	  {{ mileagerecord.mileage|stringformat:".2f" }},
      {{ mileagerecord.gallons|stringformat:".2f"|default:"null" }},
      {{ mileagerecord.mpg|stringformat:".2f"|default:"null" }}
    ]{% if not forloop.last %},{% endif %}
{% endfor %}
];
</script>
{% endblock js %}

{% block content %}
<div class="row">
  <dl class="span6">
    <dt>Stated MPG</dt><dd>{{ vehicle.stated_mpg }}</dd>
    <dt>Actual MPG</dt><dd>{{ vehicle.actual_mpg }}</dd>
    <dt>Current Mileage</dt><dd>{{ vehicle.mileage }}</dd>
  </dl>
  
  {% if mileage_form %}
  <div class="span6">
    <form method="post" class="form-horizontal" action="{% url 'mileage_new' vehicle.id %}" novalidate="novalidate">
    <div class="panel">
      <div class="header">Add Mileage</div>
      <div class="body">
        {% csrf_token %}
        {{ mileage_form|crispy }}
        <div><input type="submit" class="btn" value="Add" /></div>
      </div>
    </div>
    </form>
  </div>
  {% endif %}
</div>

  <div class="panel">
    <div class="header">History</div>
    <div class="body">
        <div id="chart"> </div>
    </div>
  </div>
  
  {% if mileage_form or not is_mobile %}
  <table id="vehicle_history" class="table table-bordered table-condensed">
    <thead>
    <tr>
      <th>Date</th>
      <th>Mileage</th>
      <th>Gallons</th>
      <th>MPG</th>
      {% if mileage_form %}
      <th>Edit</th>
      {% endif %}
     </tr>
    </thead>
    <tbody>
    {% for mileagerecord in vehicle.mileagerecord_set.reverse %}
    <tr>
      <td>{{ mileagerecord.date }}</td>
      <td>{{ mileagerecord.mileage|floatformat }}</td>
      <td>{{ mileagerecord.gallons|floatformat|default:"-" }}</td>
      <td>{{ mileagerecord.mpg|floatformat|default:"-" }}</td>
      {% if mileage_form %}
      <td>
        <a class="btn btn-mini" href="{% url 'mileage_edit' vehicle.id mileagerecord.id %}">Edit</a>
      </td>
      {% endif %}
    </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endif %}
{% endblock %}

carbonrater/mileage/templates/vehicle_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block js %}
{{ block.super }}
<script type="text/javascript">
$(function() {
  $("#id_vehicle_type").change(function() {
    if ($("#id_name").val() == "") {
      var name = $("option:selected", this).text();
      $("#id_name").val(name);
    }
  });
});
</script>
{% endblock js %}

{% block title %}{{ vehicle.name|default:"New Vehicle" }}{% endblock %}

{% block content %}
  <form method="POST" class="form-horizontal">{% csrf_token %}
  {{ form|crispy }}
    <div><input type="submit" class="btn btn-primary" value="Save" /></div>
  </form>  
{% endblock %}